### ISSUE TITLE
Issue: Class 'kartik\form\DepDrop' not found

### ISSUE THREAD

**Issue by mhashimmaqbool** [kartik-v/yii2-widget-depdrop#11]
I installed yii2-widgets via composer into my application. But when I include it in my _form.php view file, it says:

Class 'kartik\form\DepDrop' not found

I also tried including it like:
use kartik\widgets\DepDrop;

but still didn't work for me.

I then installed the individual package by:
 php composer.phar require kartik-v/yii2-widget-depdrop "*"

but it didn't resolve my problem.

**Comment by mhashimmaqbool** [comment]
Okay got it..

I used this namespace and it is working now:
use kartik\depdrop\DepDrop;

Can you please tell about what is the logic of using namespaces?. Actually some classes are included using kartik\form, some are kartik\widgets and some with there class name like kartik\depdrop.

Need clarification on it.

**Comment by kartik-v** [comment]
Read the documentation before you start install or using these extensions. As mentioned in [docs for yii2-widgets](http://demos.krajee.com/widgets) and [README for yii2-widgets](https://github.com/kartik-v/yii2-widgets/blob/master/README.md)

- you can install yii2-widgets to get all the widgets and use `kartik\widgets` namespace. 
- else you can separately install each widget from its sub repository and use it with the repo specific namespace e.g. `kartik\depdrop`, `kartik\form` etc.

**Comment by mhashimmaqbool** [comment]
Correct!
I had consulted the documentation before starting working on it. but when I installed Yii2-widgets through composer and tried to reference an active form widget into my _form.php file via "kartik\widgets" namespace, it wasn't working for me but worked with "kartik\form" namespace. That's why I was confused and asked this question. 

Anyway, I really appreciate your efforts you put in creating such great extensions for Yii2.

Thanks!

**Comment by kartik-v** [comment]
If you have installed yii2-widgets correctly & successfully - you should have no issues in using `kartik\widgets` namespace for all the widgets.

**Comment by kartik-v** [comment]
If you have installed yii2-widgets correctly & successfully - you should have no issues in using `kartik\widgets` namespace for all the widgets - UNLESS you have some problems in your composer install - in that case re-install the extension (purging it from vendor folder) or following this web tip.

If you are installing each widget extension separately - then refer to each sub repo's extension's readme (e.g. yii2-widget-depdrop, yii2-widget-activeform etc.) to understand how and what namespace to use.

**Comment by inCodeSpace** [comment]
Thanks.
