### ISSUE TITLE
The 'pluginOptions["url"]' property has not been set

### ISSUE THREAD

**Issue by emiliobruno** [kartik-v/yii2-widget-depdrop#12]
Hi Karkit,

Thanks to create that great widgets. Congratulations.
I want to use the depdrop widget, but the error: " The 'pluginOptions["url"]' property has not been set"  is ocourring. 

That is my code: 

/******* _form.php********/

<?php $atendido= ArrayHelper::map(\app\models\Clientes::find()->
				all(),'rowid','nom');?>
<?php $numprocesso= ArrayHelper::map(\app\models\Processos::find()->
				all(),'id_processo','num_processo');?>

<div class="atendimento-form">

    <?php $form = ActiveForm::begin(['type'=>ActiveForm::TYPE_HORIZONTAL]); echo Form::widget([

    'model' => $model,
    'form' => $form,
    'columns' => 2,
        
    'attributes' => [

'societe_rowid'=>['type'=>Form::INPUT_WIDGET,  //parent dropdown
            'widgetClass'=>'\kartik\widgets\Select2', 
            'options'=>['data'=>$atendido ], 
            'hint'=>'Selecione o cliente'
                        ],        
     
'id_processo'=>['type'=>Form::INPUT_WIDGET,                              //child dropdown
            'widgetClass'=>  \kartik\depdrop\DepDrop::classname(), 
                        [
                            
             'options'=>['id'=> 'processo_id' ], 
             'pluginOptions'=>[
                          'depends'=>[Html::getInputId($model, 'rowid_societe')],
                          'placeholder'=>'Selecione o processo client...',
                          //'url'=> Url::to(['/processo/subcat'])
                           'url'=> "localhost/bvb/web/index.php?r=atendimento/subcat"
                             ] ,              
                                   ]],  
//    

/*********************** AtendimentoController.php******************************************/
 public function actionSubcat() {
    $out = [];
    if (isset($_POST['depdrop_parents'])) {
        $parents = $_POST['depdrop_parents'];
        if ($parents != null) {
            $cat_id = $parents[0];
            $out = self::getSubCatList($cat_id); 
            // the getSubCatList function will query the database based on the
            // cat_id and return an array like below:
            // [
            //    ['id'=>'<sub-cat-id-1>', 'name'=>'<sub-cat-name1>'],
            //    ['id'=>'<sub-cat_id_2>', 'name'=>'<sub-cat-name2>']
            // ]
            echo Json::encode(['output'=>$out, 'selected'=>'']);
            return;
        }
    }
    echo Json::encode(['output'=>'', 'selected'=>'']);
                        }
    

Thanks in advance

Emilio

**Comment by kartik-v** [comment]
Yes the message is obvious. You need to set a valid Url in `pluginOptions['url']` using `yii\helpers\Url`.
