### ISSUE TITLE
Validation not working

### ISSUE THREAD

**Issue by rahil051** [kartik-v/yii2-widget-depdrop#14]
I have created a relationship between countries and cities using DepDrop plugin, but the validation for city drop-down is not working. The country and city attributes came from a Model based form, in which city is marked as a required field.

So when I click the submit button when there is no city selected, just a blank list, the validation message "City cannot be blank" does not show up. I haven't unfortunately found any documentation regarding validation for this package, because I thought it will work the same as a Yii Model validation system does. Here is the code.

```php
            <?= $form->field($model, 'city', [
                'options' => ['class' => '']
            ])->widget(DepDrop::className(), [
                'options' => [
                    'id' => 'city-select',
                    'class' => 'registration-input test'
                ],
                // 'data' attr is populated with pre-selected cities upon a $_POST request
                'data' => call_user_func(function ($data) {
                    if($data) {
                        $countryCode = $data['SignupForm']['country'];
                        $cityModel = WCity::findAll(['CountryCode' => $countryCode]);
                        $cityArr = [];
                        foreach($cityModel as $city) {
                            $cityArr[$city->ID] = $city->Name;
                        }

                        return $cityArr;
                    } return [];
                }, $postData),
                'pluginOptions' => [
                    'depends' => ['country-select'],
                    'placeholder' => 'Select...',
                    'url' => Url::to(['/site/populate-city-dropdown'])
                ]
            ])->label(false) ?>
```

**Comment by emiliobruno** [comment]
Hi Rahil,

Change the ['depends'] parameter this way:

  'depends'  =>  ['city-select'],

This should works.

Cheers

Emilio


>              <?=  $form->field($model,'city', [
>                  'options'  =>  ['class'  =>  '']
>              ])->widget(DepDrop::className(), [
>                  'options'  =>  [
>                      'id'  =>  'city-select',
>                      'class'  =>  'registration-input test'
>                  ],
>                  // 'data' attr is populated with pre-selected cities upon a $_POST request
>                  'data'  =>  call_user_func(function  ($data) {
>                      if($data) {
>                          $countryCode  =  $data['SignupForm']['country'];
>                          $cityModel  =  WCity::findAll(['CountryCode'  =>  $countryCode]);
>                          $cityArr  =  [];
>                          foreach($cityModel  as  $city) {
>                              $cityArr[$city->ID]=  $city->Name;
>                          }
>
>                          return  $cityArr;
>                      }return  [];
>                  },$postData),
>                  'pluginOptions'  =>  [
>                      'depends'  =>  ['country-select'],
>                      'placeholder'  =>  'Select...',
>                      'url'  =>  Url::to(['/site/populate-city-dropdown'])
>                  ]
>              ])->label(false)?>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/kartik-v/yii2-widget-depdrop/issues/14>.
>


--

**Comment by rahil-geekunit** [comment]
@emiliobruno Thanks for your reply, but I think this case can not resolve the issue. Because I can not make the city dropdown to depend on itself.

The city DepDrop plugin should have the
```php
'pluginOptions' => [ 'depends' => ['country-select'] ]
```
otherwise, it will not work as intended. I think there should be another way.

**Comment by rahil-geekunit** [comment]
I have finally resolved that issue. The problem was causing by assigning an incorrect HTML IDs to both parent and child dropdown.
I was using a model form which automatically applies validation by reading the rules from the model class. When the form is submitted, the validation styling is applied by reading the correct version of ID. For example the ID for a country field associated with a "Signup" model form, generated by the framework will look like this,
```
id="signupform-country"
```
same for the city
```
id="signupform-city"
```
but I was applying my own ID, instead of the Yii one, which was causing the validation not to appear,
so the final code will look something like this
```php
<?= $form->field($model, 'country')->dropDownList($countriesDropdown, [
   'class' => 'registration-input test', 
   'id' => 'signupform-country' // the id from Yii 2, get the ID hint from Browser Developer Tools
]) ?>

<?= $form->field($model, 'city')->widget(DepDrop::className(), [
    'options' => [
        'class' => 'registration-input test',
        'id' => 'signupform-city'
    ],
    'data' => call_user_func(function ($data) {
        if($data) {
            $countryCode = $data['SignupForm']['country'];
            $cityModel = WCity::findAll(['CountryCode' => $countryCode]);
            $cityArr = [];
            foreach($cityModel as $city) {
                $cityArr[$city->ID] = $city->Name;
            }

            return $cityArr;
        } return [];
    }, $postData),
    'pluginOptions' => [
        'depends'  =>  ['signupform-country'],
        'placeholder' => 'Select...',
        'url' => Url::to(['/site/populate-city-dropdown'])
    ]
]) ?>
```

**Comment by rahil051** [comment]
^ That was my office github account.

**Comment by rahil-geekunit** [comment]
jhghjghj
