### ISSUE TITLE
[initialize = true] do not work sometimes

### ISSUE THREAD

**Issue by aleksanderd** [kartik-v/yii2-widget-depdrop#16]
It work ok most times, but 1-2 times for ~10 tries I have empty value for last selector :( The list is loaded ok and able to select, but value of the field is lost :(

**Comment by kartik-v** [comment]
This is resolved with latest release of `kartik-v/dependent-dropdown` plugin. Check the updated demos.

**Comment by aleksanderd** [comment]
Huge thnx, but now it is always empty value :( I noticed in my case work this line: [return false](https://github.com/kartik-v/dependent-dropdown/blob/master/js/dependent-dropdown.js#L69) since I use Select2.

**Comment by kartik-v** [comment]
You need to check the documentation and demos closely again on HOW you need to set your nested dependency. Check the [demo page for usage](http://demos.krajee.com/widget-details/depdrop#advanced-usage) with Select2.

Also note that if you need to set a value via ajax ... you need to return the `selected` property with your json data.

**Comment by aleksanderd** [comment]
I "smoking" the docs second day :) May be you can find a minute to review my code plz?
~~~php
if (Yii::$app->user->identity->isAdmin) {
    $userData = ArrayHelper::map(User::find()->asArray()->all(), 'id', 'username');
    echo $form->field($model, 'user_id')->widget(Select2::className(), [
        'data' => $userData,
        'hideSearch' => true,
        'pluginOptions' => [
            'placeholder' => $userPlaceholder,
            'allowClear' => true,
        ],
    ])->label(Yii::t('app', 'User'));
} else {
    echo Html::activeHiddenInput($model, 'user_id');
}

echo $form->field($model, 'site_id')->widget(DepDrop::className(), [
    'type' => DepDrop::TYPE_SELECT2,
    'data' => [$model->site_id => 'xxx'],
    'pluginOptions' => [
        'placeholder' => $sitePlaceholder,
        'url' => Url::toRoute('client-site/select-list'),
        'depends' => ['variable-user_id'],
//        'initDepends' => ['variable-user_id'],
//        'initialize' => true,
    ],
    'select2Options' => [
        'hideSearch' => true,
        'pluginOptions' => [
            'allowClear' => true,
        ],
    ],
])->label(Yii::t('app', 'Site'));

echo $form->field($model, 'page_id')->widget(DepDrop::className(), [
    'type' => DepDrop::TYPE_SELECT2,
    'data' => [$model->page_id => 'xxx'],
    'pluginOptions' => [
        'placeholder' => $pagePlaceholder,
        'url' => Url::toRoute('client-page/select-list'),
        'depends' => ['variable-user_id', 'variable-site_id'],
        'initDepends' => ['variable-user_id', 'variable-site_id'],
        'initialize' => true,
    ],
    'select2Options' => [
        'hideSearch' => true,
        'pluginOptions' => [
            'allowClear' => true,
        ],
    ],
])->label(Yii::t('app', 'Page'));
~~~
The actions do not returns 'selected' at all, just 'output'...


After some modest research, I found if I change this line in `init` function:
~~~js
self.setDep($id, depends, len, false);
~~~
to
~~~js
self.setDep($id, depends, len, $el.val());
~~~
it work but excepting last child...

Also, some value issues in `beforeSend` callback of `proccessDep`. For ex., if I add:
~~~js
var elVal = $el.val();
~~~
at the first line of `processDep`, and add:
~~~js
if (selected === null) {
  selected = elVal;
}
~~~
at second to `success` callback of `processDep`, its also work, but except last child again...

thnx

**Comment by kartik-v** [comment]
In the last child dropdown change your widget plugin configuration to the following:

```php
[
'initDepends' => ['variable-user_id'],  // this should be the topmost parent
'depends' => ['variable-site_id'], // this should be the immediate parent
'initialize' => true
]
```

**Comment by kartik-v** [comment]
In the last child dropdown change your widget plugin configuration to the following:

```php
[
'initDepends' => ['variable-user_id'],  // this should be the topmost parent
'depends' => ['variable-site_id'], // this should be the immediate parent
'initialize' => true
]
```

Also ensure you got the latest code for **kartik-v/yii2-widget-select2, kartik-v/yii2-widget-depdrop, and kartik-v/dependent-dropdown**

**Comment by aleksanderd** [comment]
Huge thnx! It make understaning `depends` and `initDepends` more clear.
... And it works! But only if I change [one line](https://github.com/kartik-v/dependent-dropdown/blob/master/js/dependent-dropdown.js#L71) in `init` :)
from:
~~~js
self.setDep($id, depends, len, false);
~~~
to:
~~~js
self.setDep($id, depends, len, $el.val());
~~~

Could you explain what the false means here? The parameter seems to be for the value, but there is only one call with 'false' :o
Btw, why not to just store current value in a variable at begining of `proccessDep` and restore it if nothing other given at `success` callback, instead of passing the value as param thru several calls?

thnx!
// using dev-master for all 3 packages
// also, just deleted and regrabbed them with 'composer up'

**Comment by aleksanderd** [comment]
Also, I just noticed, Select2 clear action do not fire the refreshing of deps. Just yerstarday it was ok.

**Comment by kartik-v** [comment]
As mentioned before - 

Ensure you got the latest code updated for **kartik-v/yii2-widget-select2, kartik-v/yii2-widget-depdrop, and kartik-v/dependent-dropdown**

There are updates to all the above extensions.

I fixed the above as well for `$el.val()` initialization - but note --- if you are passing the `selected` from your ajax server code it should get overwritten.

**Comment by kartik-v** [comment]
As mentioned before - 

Ensure you got the latest code updated for **kartik-v/yii2-widget-select2, kartik-v/yii2-widget-depdrop, and kartik-v/dependent-dropdown**

There are updates to all the above extensions.

I fixed the above as well for `$el.val()` initialization - but note --- if you are passing the `selected` from your ajax server code it should get anyway overwritten and it is recommended if you want to set default value for each dropdown after every change to a dependent parent.

**Comment by aleksanderd** [comment]
composer.json part:
~~~json
...
        "kartik-v/yii2-widget-select2": "dev-master",
        "kartik-v/dependent-dropdown": "dev-master",
        "kartik-v/yii2-widget-depdrop": "dev-master",
...
~~~
is it ok?
Also, I see your just made changes by 'composer up'

Anyway, for now all ok... almost :) The 'clear' of **DepDrop** widgets work ok, but 'clear' of **Select2** (`user_id` most parent widget in my case code abobe) - still not fire ajax connects for the childs :(

Also, I noticed(after today updates), there is 'open/close' of child selector's when 'clear' clicked.

thnx

**Comment by kartik-v** [comment]
With regards Select2 ---  [refer this issue](https://github.com/kartik-v/yii2-widget-select2/issues/42) There is an issue in the Select2 plugin which is been reported to the [Select2 Plugin team](https://github.com/select2/select2/issues/3320) 

I have provided a temporary workaround fix (hack) in the yii2-widget-select2 to overcome the above issue. It ideally should get resolved completely once the fix is provided in the plugin.

**Comment by kartik-v** [comment]
Ok this is resolved now - update all via composer.

**Comment by aleksanderd** [comment]
Huge thanks!

but It seems the very last update add new 'clear' related issue. Now it fire ajax, but with previous(not 0|null) id.

**Comment by kartik-v** [comment]
Resolved now.

**Comment by aleksanderd** [comment]
Seems to be all ok for now :)
Thanks!
