### ISSUE TITLE
DepDrop::Select2 multiple select option not working

### ISSUE THREAD

**Issue by maverick3609** [kartik-v/yii2-widget-depdrop#19]
Hi

In DepDrop with Select2 the option for multiple select is not working. For reference my code is given as below - 

 <?= $form->field($model, 'sections')->widget(DepDrop::className(), [
                        'options' => ['placeholder' => 'Select ...'],
                        'type' => DepDrop::TYPE_SELECT2,
                        'select2Options' => [
                            'options' => ['multiple' => true],
                            'pluginOptions'=>['allowClear' => true]
                        ],
                        'pluginOptions' => [
                            'depends' => ['form-exam', 'form-type'],
                            'url' => Url::to(['form/section']),
                            'loadingText' => 'Loading Sections ...',
                        ]
                    ]) ?>

**Comment by nagyt234** [comment]
+1
Some additional information. There are two problems:
1. The placeholder text appears in select2 as a selected value.
2. The POST request generate contains a simple value (the last selected one) instead of an array.

I have a very similar config (the example is using FormGrid):
```
            'region_list' => [
                'columnOptions' => [ 'colspan' => 2 ],
                'type' => Form::INPUT_WIDGET,
                'widgetClass' => DepDrop::className(),
                'options' => [
                    'data' => $region_data,
                    'type' => DepDrop::TYPE_SELECT2,
                    'select2Options' => [
                        'pluginOptions' => [
                            'multiple' => true,
                            'allowClear' => true,
                            'placeholder' => Module::t('app','Select a region...'),
                            'clientOptions' => $updateAllowed ? 'enable' : 'disable',
                        ],
                    ],
                    'pluginOptions' => [
                        'depends' => ['recipe-cuisine_list'],
                        'url' => Url::to(['recipe-param/depdrop']),
                        'placeholder' => Module::t('app','Select a region...'),
                    ],
                ],
            ],

```

**Comment by saada** [comment]
+1
@maverick3609 , 
In addition to@nagyt234:
3. Return the "selected" key on the server side does not preselect the value with both array `[1,2,3]` and string `"1,2,3"` formats.

I am unable to handle the UPDATE cases properly in addition to all the above issues.

**Comment by atiq1589** [comment]
Hi,
For me select multiple working. Just put **_'multiple' => true_** under pluginOptions. 
It should look like this 
`['pluginOptions' => ['allowClear' => true, 'multiple' => true]]`
