### ISSUE TITLE
Could not parse version constraint <=2.*: Invalid version string "2.*"

### ISSUE THREAD

**Issue by msstoci** [kartik-v/yii2-widget-depdrop#20]
Basic usage: composer <command>
For more information just type "composer".

C:\xampp\htdocs\ikpmrbogor>composer require kartik-v/yii2-widget-depdrop "@dev"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

  [UnexpectedValueException]
  Could not parse version constraint <=2.*: Invalid version string "2.*"

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update]
[--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-
packages] [packages1] ... [packagesN]

C:\xampp\htdocs\ikpmrbogor>

**Comment by kartik-v** [comment]
You may need to check your application's composer settings and dependencies.

If you need programming tips and help a new Q & A forum has been created for such use and you can [search and ask for questions/help out there](http://webtips.krajee.com/questions).
