### ISSUE TITLE
handling null values

### ISSUE THREAD

**Issue by akorinek** [kartik-v/yii2-widget-depdrop#21]
I've got a depdrop in an active form for a field. Everything works, except when the field value is null. Then the first entry in the list gets selected.
Is there a way around this?

if (!empty($model->user->customer_id)) {
            $data = Customer::getBillingProfilesDropdown2($model->user->customer_id);  
        } else {
            $data = [];
        }
        
        echo $form->field($model,'billingprofile_id')->widget(DepDrop::className(), [
            'options' => ['id' => 'billingprofile_id'],
            'type' => DepDrop::TYPE_SELECT2,
            'select2Options' => ['pluginOptions' => ['allowClear' => true]],
            'data' => $data,
            'pluginOptions' => [
                'depends' => ['booking-user_id'],
                'prompt' => 'select billing profile...',
                'url' => Url::to(['customer/dropdownbillingprofile']),
            ]
        ]);

**Comment by kartik-v** [comment]
That's how the default native SELECT input behaves. You may want to add the placeholder property in pluginOptions of the DepDrop to show a null value correctly.
