### ISSUE TITLE
Allow specifying how parent params are named

### ISSUE THREAD

**Issue by rimas-kudelis** [kartik-v/yii2-widget-depdrop#24]
Currently the names of parent parameters passed to the backend via the `POST` request are hardcoded: parents are always passed as `depdrop_parents[]` and `depdrop_all_params[]`. It would be nice if these names could be changed via widget configuration, so that we the developers wouldn't have to tie our controllers to this particular implementation of the dependent dropdown widget.

**Comment by kartik-v** [comment]
Will be resolved via the enhancement at kartik-v/dependent-dropdown#34.
