### ISSUE TITLE
Widget populates Select properly but not selected option

### ISSUE THREAD

**Issue by dbd5** [kartik-v/yii2-widget-depdrop#26]
Hello,

I have a very simple use case where at the backend I have the following setup;

    public function actionStrength()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];

            if ($parents != null) {
                $testconfig_id = $parents[0];
                $strength=\common\models\Testconfig::findOne($testconfig_id)->strength;
                    $out = [
                        ['id'=>'1', 'name'=>'Easy'],
                        ['id'=>'2', 'name'=>'Normal'],
                        ['id'=>'3', 'name'=>'Difficult'],
                    ];
                    $selected=strval($strength);
                echo Json::encode(['output'=>$out, 'selected'=>$selected]);
                return;
            }
        }
        echo Json::encode(['output'=>'', 'selected'=>'']);
    }

The logs show the backend is returning the correct json data as follows (notice the selected element is "3")
{"output":[
	{"id":"1","name":"Easy"},
	{"id":"2","name":"Normal"},
	{"id":"3","name":"Difficult"}
	],
	"selected":"3"
}

The issue is that the item selected from the backend is not selected by the widget even though it populates properly. Please advise as all the rules have been followed.

Regards,

Adam

**Comment by dbd5** [comment]
The configuration of the widget is as follows;

             echo $form->field($model, 'strength')->widget(DepDrop::classname(), [
                'options' => ['id'=>'test-strength-list'],
                'pluginOptions'=>[
                    'depends'=>['test-config-list'],
                    'initialize'=>true,
                    'placeholder' => false,
                    'url' => Url::to(['/testpaper/strength'])
                ]
            ]);

**Comment by kartik-v** [comment]
Not sure why... looks ok... but you may want to debug a bit further.

You can cross check [with the example scenario 3 on the advanced usage demo](http://demos.krajee.com/widget-details/depdrop#advanced-usage). Just change `Lev1` from `Bank` to `Cash` or vice-versa to check on your chrome dev console.

**Comment by dbd5** [comment]
Hi Kartik,

Right now when the parent list changes, depdrop shows the FIRST element from the returned list as selected when 'placeholder'=>false or it shows 'Select...' when 'placeholder'=>'Select...' which means it really doesn't select anything at all.

Per your instruction,  I've looked and there are no errors in my chrome javascript console.

I've also been looking at the source, it appears that the comparison to decide the selected element is done in line 20 of dependent-dropdown.js reproduced below;

if (sel !== null && sel.length && id.toString() === sel) {

Judging from the data returned by Json in the logs reproduced, I'm fairly confident that "selected":"3" meets all the requirements when javascript compares it with id in line 20 ("3" is not null, "3".length > 0, "3" is equal value and equal type to "id":"3"  (===) ) 

I also note that all the depdrop in the example 3 scenario advanced usage demo selects the FIRST item from the returned list (which may be valid if the logic in the backend controller actually selects the first in each case, I have no way of knowing)

Is it possible that due to some logic flow issue this comparison is not even done and so the first item is returned by default?

Sorry to bother you so much and of course I mean no disrespect. You could reproduce my code in 5 minutes when you have time.

The line $strength=\common\models\Testconfig::findOne($testconfig_id)->strength; simply queries the Testconfig table and returns the strength field from a table with 4 records in which for the purpose of testing I have set all values of strength column to 3 (Difficult), the other possibilities are 1 (Easy) and 2 (Normal)

Thank you for all your support.

Regards,


Adam

**Comment by kartik-v** [comment]
Seems this is more an issue with SELECT 2 plugin - I will push in a fix for this.

**Comment by kartik-v** [comment]
Resolved via upgrade to [release v1.0.3](https://github.com/kartik-v/yii2-widget-depdrop/commit/571811de9249ad5bb7f14e04d63674f4c8afebf4)

**Comment by rubenzablocki** [comment]
Hi guys, i have problem with default selection of my dropdown lists. I have 3 dropdowns and all selection of this lists are stored in the model.
But when i open update view only first dropdown has selected option (classic dropDownListelement from Yii), on the rest of DepDrop dropdownlists default selection is not working.
Please help me to find what i'm doing wrong.

VIEW:
`
$form->field($model, 'price_type_id')->dropDownList($priceTypes, ['prompt'=>'--- Select ---', 'class' => 'price-type', 'id'=>'price_type_id', 'disabled' => $disabled])->label('Extra price');

$form->field($model, 'price_table_id')->widget(DepDrop::classname(), [
      'options' => ['id'=>'price_table_id'],
      'pluginOptions'=>[
           'depends'=>['attribute_id', 'price_type_id'],
           'initialize' => true,
            'placeholder' => '--- Select price table ---',
            'url' => Url::to(['//attribute-item/get-price-tables'])
     ],
])->label('Price table');
 
$form->field($model, 'price_group_id')->widget(DepDrop::classname(), [
     'options' => ['id'=>'price_group_id'],
     'pluginOptions'=>[
          'depends'=>['attribute_id', 'price_type_id', 'price_table_id'],
          'initialize' => true,
          'placeholder' => '--- Select price group ---',
          'url' => Url::to(['//attribute-item/get-price-table-groups'])
     ],
])->label('Price groups');
`

CONTROLLER:

`
public function actionGetPriceTables() {
        $priceTables = null;
        if (Yii::$app->request->isAjax && Yii::$app->request->post('depdrop_parents')) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $modelId = $parents[0];
                $model = $this->findModel($modelId);
                $priceTables = $model->getPriceTables()->asArray()->all();             
            }
        }
        echo json_encode(['output' => $priceTables, 'selected' => $model->price_table_id]);
    }

public function actionGetPriceTableGroups() {
        $priceGroups = null;
        if (Yii::$app->request->isAjax && Yii::$app->request->post('depdrop_parents')) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $modelId = $parents[0];
                $model = $this->findModel($modelId);
                $priceTableId = $parents[2];
                
                $priceGroups = PriceGroup::find()->where(['price_table_id' => $priceTableId])->asArray()->all();
            }
        }
        echo json_encode(['output' => $priceGroups, 'selected' => $model->price_group_id]);
    }
`

**Comment by Mehul-Vaghela** [comment]
Hi @kartik-v 
<?php
                                    echo Select2::widget([
                                        'initValueText' => $chemicals->chemical,
                                        'value' => $chemicals->chemical,
                                        'disabled' => $readonly,
                                        'hideSearch' => true,
                                        'name' => 'ManagersChecklistDaily[chemical_usage_recorded_text][' . $key . '][chemical]',
                                        'data' => $ch_data,
                                        'maintainOrder' => true,
                                        'options' => [
                                            'placeholder' => 'Select chemical ...',
                                            'multiple' => false
                                        ],
                                        'pluginOptions' => [
                                            'tags' => true,
                                            'allowClear' => true,
                                        ],
                                    ]);
                                    ?>
This is my code and when I search the keyword is appended in drop-down even if it is not existed in array.will you please guide me about this.I don't want to allow typed word if not match found
