### ISSUE TITLE
Select all button does not initialize controller with multiple select2

### ISSUE THREAD

**Issue by KirillRyzhkov** [kartik-v/yii2-widget-depdrop#28]
If to press Select all button the ajax request is not initializing. If I select tags one by one the controller action is working fine. My code
<strong>_form</strong>

<pre>
<?= $form->field($user, 'country_region')->widget(Select2::classname(), [
    'data'=> ['ee'=>'Europe', 'pa' => 'Pacific'],
    'options' => [
        'placeholder' => 'Select regions',
        'multiple' => true
    ],
    'pluginOptions'=>[
        'allowClear' => true,
    ]
]);
?>

<?= $form->field($user, 'country_field')->widget(DepDrop::classname(), [
    'data' => $user->DropCountry,
    'options' => [
        'placeholder' => 'Select countries',
        'multiple' => true
    ],
    'type' => DepDrop::TYPE_SELECT2,
    'select2Options'=>['pluginOptions'=>['allowClear'=>true]],
    'pluginOptions'=>[
        'depends'=>[Html::getInputId($user, 'country_region')],
        'url' => Url::to(['/user/admin/country-region']),
        'loadingText' => 'Loading countries',
    ]
]);
</pre>

<strong>Controller</strong>

<pre>
public function actionCountryRegion() {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $id = end($_POST['depdrop_parents']);
            $list = Countries::find()->andWhere(['region'=>$id])->asArray()->all();
            $selected  = null;
            if ($id != null && count($list) > 0) {
                $selected = '';
                foreach ($list as $i => $account) {
                    $out[] = ['id' => $account['country'], 'name' => $account['country_name']];
                    if ($i == 0) {
                        $selected = $account['country'];
                    }
                }
                // Shows how you can preselect a value
                echo Json::encode(['output' => $out, 'selected'=>$selected]);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected'=>'']);
    }
</pre>

**Comment by crestoff** [comment]
+++

**Comment by fateevv85** [comment]
you need to edit 'dependent-dropdown.js' in your assets directory.
on line 97,
before: on('depdrop:change change select2:select krajeeselect2:cleared'
after: on('depdrop:change change select2:select krajeeselect2:cleared krajeeselect2:selectall krajeeselect2:unselectall'
this is help me.

**Comment by kimhongn89** [comment]
fateevv85 You right.
Can you update for this case Kartik :)

**Comment by kartik-v** [comment]
Will check and update

**Comment by tarmof** [comment]
Still this is not working. Select all does not trigger any action

**Comment by lromanut** [comment]
Any solution?
