### ISSUE TITLE
The 'pluginOptions["url"]' property has not been set.

### ISSUE THREAD

**Issue by kmaurya125** [kartik-v/yii2-widget-depdrop#3]
Hi,

It's not an issue just a suggestion.
I tried to implement it as per instruction but got below mentioned error in "vendor\kartik-v\yii2-widget-depdrop\DepDrop.php" on line 57.
Invalid Configuration – yii\base\InvalidConfigException
The 'pluginOptions["url"]' property has not been set.

after comparing with example "https://github.com/kartik-v/yii2-widget-depdrop" I found have you are using the class without define URL.
echo $form->field($account, 'lev0')->widget(Select2::classname(), [
    'data' => ArrayHelper::map(Account::find()->where('parent IS NULL')->asArray()->all(), 'id', 'name')
]);

Please change that in documentation. Thanks

**Comment by kartik-v** [comment]
The documentation is correct. The `pluginOptions['url']` is only required for the DepDrop widget not for the topmost parent. The code you pasted above is for the parent and is not rendered using the DepDrop widget at all: 

```php
echo $form->field($account, 'lev0')->widget(Select2::classname(), [
    'data' => ArrayHelper::map(Account::find()->where('parent IS NULL')->asArray()->all(), 'id', 'name')
]);
```
