### ISSUE TITLE
Is composer dev version in the doc should be change to release version?

### ISSUE THREAD

**Issue by dogrocker** [kartik-v/yii2-widget-depdrop#31]
Hello I have used depdrop on my project but some thing confuse me about the Doc.

in the doc told me to use `"@dev"` version

But I've seen your create the release version now is `1.0.4`.

So for stable user that use the depdrop and don't want the major update of depdrop in the future,

The doc should be change to version of release right ?

Thanks.

**Comment by kartik-v** [comment]
It entirely depends on each developer as to what version they want to install.

**Comment by dogrocker** [comment]
Thanks for suggestion.
