### ISSUE TITLE
How to reload/refresh dependent dropdown manually?

### ISSUE THREAD

**Issue by sotwarrior** [kartik-v/yii2-widget-depdrop#32]
For example, I have two DropDep, A and B.
I assigning the value for A manually, $(A).val(12).trigger('change'), and I want to refresh B control after A changed. How to do that?

**Comment by lidiexy** [comment]
Same Question.??? +1

**Comment by mcrosales** [comment]
I have the same doubt. Has anyone managed to find a solution, whitout refreshing the whole component via ajax, for example?? Thanks in advance

**Comment by kartik-v** [comment]
Yes just trigger the `change` event on your parent dropdown via javascript.
