### ISSUE TITLE
Validation not working on dependent field

### ISSUE THREAD

**Issue by KirillRyzhkov** [kartik-v/yii2-widget-depdrop#36]
Validation only works for parent dropdown.
In the model I have

<pre>
['event_field', 'status_field'], 'required']
</pre>

<pre>
<div class="col-md-6">
<?= $form->field($model, 'event_field')->dropDownList(ArrayHelper::map(OrdersStage::find()->asArray()->all(), 'stage_id', 'stage_name'), ['id'=>'e_id', 'prompt'=>'']); ?>
        </div>
        <div class="col-md-6">
            <?php
                echo $form->field($model, 'status_field')->widget(DepDrop::classname(), [
                    'options'=>['id'=>'substatus-id'],
                    'pluginOptions'=>[
                        'depends'=>['e_id'],
                        'placeholder'=>'',
                        'url' => Url::to(['/orders/events-group']),
                        'loadingText' => 'Loading statuses...',
                            'initialize'  => false,
                    ]
            ]);
            ?>
        </div>
</pre>

If status_field is empty validation is not triggered.

**Comment by felipe-carrasco** [comment]
Did you sorted it out? I'm facing similar issue.

**Comment by KirillRyzhkov** [comment]
No, I haven't figured it out just left them without validation.

**Comment by rnunot** [comment]
I was having the same issue, the problem is the custom id.

http://demos.krajee.com/widget-details/depdrop#comment-2081535866
https://github.com/yiisoft/yii2/issues/7627

**Comment by is7** [comment]
Required in rules second dropdown is not validating after parent dropdown value returned to default ''=>'Please select'. Issue is in the disabled second dropdown and 'blur' event on it. 

Quick fix of this issue is to add depdrop:afterChange pluginEvent like this: 

`'pluginEvents' => [
        "depdrop:afterChange"=>"function(event, id, value) { 
            if (value == '') {
                $('#second-dropdown-id').prop('disabled',false).blur();
                window.setTimeout(function() {
                    $('#second-dropdown-id').prop('disabled',true); 
                },500);
            }
        }",
    ],`
