### ISSUE TITLE
TypeError: invalid 'in' operand obj while using kartik\depdrop\DepDrop;

### ISSUE THREAD

**Issue by Raviiikgh** [kartik-v/yii2-widget-depdrop#37]
Hi Kartik,

I am developing depending dropdown using **yii2-widget-depdrop** now while i hit on SelecBox the output by controller is fine (as i have crossed check in Inspect Element) but it gives me an error like
 `**TypeError: invalid 'in' operand obj**` 
What should i do now ?

Please help me out.
Thanks in Advance :)

**Comment by kepingatp** [comment]
Hi, Have you solved this issue yet? 
I also has faced this issue too.
Thanks.

**Comment by component6** [comment]
Hello. I also have this error. Please help

jQuery JavaScript Library v2.2.4

**Comment by Coolkop** [comment]
yii\helpers\ArrayHelper::map makes incorrect array for dropdown. 
It generates array like 
```php
$out = [
    [2, 'first-items-name'],
    [43, 'second-items-name'],
    ...
]
``` 
Correct array 
```php
$out = [
    ['id'=>2, 'name'=>'first-items-name'],
    ['id'=>43, 'name'=>'second-items-name'],
    ...
]
```
