### ISSUE TITLE
 plugin event - "depdrop.init"

### ISSUE THREAD

**Issue by NatalyMac** [kartik-v/yii2-widget-depdrop#39]
Hi:)
does it work?   "depdrop.init"
i try   "depdrop.init"=>"function() { log('depdrop.init'); }",
in my code 
<?=$form->field($model, 'city_id')->widget(DepDrop::className(), [
        'options'=>['id'=>'city_id-id'],
        'pluginEvents'=> [
            "depdrop.init"=>"function() { log('depdrop.init'); }",
            //"depdrop.afterChange"=>"function(event, id, value) { console.log('value: ' + value + ' id: ' + id); }"
        ],
        'pluginOptions'=>[
            'depends'=>['district_id-id'],
            'initialize' => true,
            'placeholder'=>'Select...',
            'url'=>Url::to(['/city/lists?id=']),
                //.$model->city_id])
        ],
    ]);?>

but do not watch  anything in the console log
"depdrop.afterChange" works, but i need event init. How i can do it? Thank you

**Comment by strtob** [comment]
I have the same issue, can anybody help? :-/
