### ISSUE TITLE
Event issue (depdrop.afterChange)

### ISSUE THREAD

**Issue by YairHadari** [kartik-v/yii2-widget-depdrop#4]
Hi,

I would like to thank kartik for his contribution to the community with this great plugin.

Unfortunately I have a problem with the depdrop.afterChange.

I have the following Active Form:

    <?php $form = ActiveForm::begin([
	])
    ?>   

    <?php $dataMenu=ArrayHelper::map(\frontend\models\menutype::find()->asArray()->all(), 'menuTypeID', 'MenuTypeDesc'); ?>

    <?= $form->field($model, 'masterMenuTypeID')->dropDownList($dataMenu, ['id'=>'MenuType-id', 'prompt'=> 'Select Dish Type...']); ?>

    <?= $form->field($model, 'masterMenuTypeDishID')->widget(DepDrop::classname(), [
   	'options'=>['id'=>'MenuTypeDish-id'],
   	'pluginEvents'=> [
    		"depdrop.afterChange"=>"function(event, id, value) { console.log('value: ' + value + ' id: ' + id); }"
	],
    	'pluginOptions'=>[
        	'depends'=>['MenuType-id'],
	       	'placeholder'=>'Choose...',
		'loadingText'=>'Loading...',
	        'url'=>Url::to(['/master_menu/dish_type'])        
    	]]); ?>

    <?php ActiveForm::end(); ?>

The output of the depdrop.afterChange event give me the value of the previous form field.
The out put is:
 value: 1 id: MenuType-id

Please note the ID. This is the ID of the first field and not the ID where the event is triggered from.

Thanks for your help,
Yair

**Comment by YairHadari** [comment]
Ok, I understood the event is displaying the dependent parent input and not the current depend.
If this is true and the current depend is the last one, how can I get the events this depend is issuing?

Thanks again,
Yair

**Comment by kartik-v** [comment]
do not complicate it... its a normal `change` event for the last child... :-) . 

The `depdrop.change` event is triggered on a child select whenever its dependent parent changes the value.

**Comment by YairHadari** [comment]
Kartik,

Thanks for the fast reply.
I don't want to be rood but may be you can give me an example of a normal
change event for the last child?

Thanks in advance,
Yair

**Comment by kartik-v** [comment]
- If you have 3 dropdowns  with ids say: A, B, & C.  
- B is dependent on A
- C is dependent on B

```js

$('#B').on('depdrop.afterChange', function(event, id, value) {

});
```

**Comment by kartik-v** [comment]
- If you have 2 dropdowns  with ids say: A, B
- B is dependent on A

```js

$('#B').on('depdrop.afterChange', function(event, id, value) {
    // id  will return "A"
   // value will return $("#A").val();
});

// the last child
$('#B').on('change', function(event) {
    var id = $(this).attr('id'), val = $(this).val();
    // id  will return "B"
   // value will return $("#B").val();
});
```

**Comment by sotwarrior** [comment]
How to refresh dropdown B in case if new value assigned for A (i.e. $('#A').val(10).trigger('change'))?
Dropdown B stays disabled and not refreshed, but if I select new value from dropdown A manually - it works as expected. Please advise.

**Comment by mcrosales** [comment]
I have a similar issue. I want to refresh the options in the child after manual change of the father, like sotwarrior suggested: $('#father').val(10).trigger('change'). How can this be achieved?? Thanks in advance.

**Comment by muhammad1992** [comment]
@mcrosales 
You need to do this:
$('#father').val(10).trigger('change').trigger('depdrop:change');

**Comment by kartik-v** [comment]
> How to refresh dropdown B in case if new value assigned for A (i.e. $('#A').val(10).trigger('change'))?
Dropdown B stays disabled and not refreshed, but if I select new value from dropdown A manually - it works as expected. Please advise.

Yes trigger both the `change` and `depdrop:change` events as @muhammad1992  mentioned
