### ISSUE TITLE
Repeating ajax request on new DepDrop field

### ISSUE THREAD

**Issue by soorajerajeevan** [kartik-v/yii2-widget-depdrop#40]
I have 4 drop downs in which one is parent and all other 3 are depending on parent

>   _parent_
>  _child_1_
>  _child_2_
>  _child_3_

I tried to create one more child say _child_4_ with default options
by  calling this command 

`$('#child_4').depdrop('init');` 

Result was all other child are sending same AJAX request again and goes back to "Select...."

How to init only my new child???  I need to keep other selected child untouched..

**Comment by tiagomv94** [comment]
someone?

**Comment by kartik-v** [comment]
You need to control the dependency to ensure how many ajax requests fire accordingly. If you have set 3 different dropdowns to depend on the same parent... it is natural that whenever the parent changes, there will be 3 ajax requests will fire.
