### ISSUE TITLE
Showing an error URL not found

### ISSUE THREAD

**Issue by PradeepN93** [kartik-v/yii2-widget-depdrop#46]
Hi kartik-v,
I have used your plugin depdrop, and it gives an error 'URL' not found Please help....

In Form page i added this
<?= $form->field($model, 'crop_category')->dropDownList($pc,['id'=>'cat-id'],['prompt'=>'- Choose Crop Category -'])->label('Crop Category');  ?>

<?= $form->field($model, 'crop_productlist')->widget(DepDrop::classname(), [
        'data' => [$model->crop_productlist=>$model->crop_productlist],
         'options' => ['id'=>'subcat-id'],
         'pluginOptions'=>[
             'depends'=>['cat-id'],
             'placeholder' => 'Select...',
             'url' => Url::to(['/site/subcat'])
         ]
     ]); ?>

And controller i added this

public function actionSubcat() {
        
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $cat_id = $parents[0];
                $out = self::getSubCatList($cat_id); 

                $pl = ProductList::find()->where(['prolist_id' =>$cat_id])->all();
                 $all_pl = array();
                $i = 0;
                foreach ($pl as $value) {
                    $all_pl[$i]['prolist_id'] = $value['prolist_id'];
                    $all_pl[$i]['prolist_name'] = $value['prolist_name'];
                    $i++;
                }

                // the getSubCatList function will query the database based on the
                // cat_id and return an array like below:
                // [
                //    ['id'=>'<sub-cat-id-1>', 'name'=>'<sub-cat-name1>'],
                //    ['id'=>'<sub-cat_id_2>', 'name'=>'<sub-cat-name2>']
                // ]
                echo Json::encode(['output'=>$all_pl, 'selected'=>'']);
                return;
            }
        }
        echo Json::encode(['output'=>'', 'selected'=>'']);
    }

**Comment by kennethabuelxd** [comment]
use yii\helpers\Url;
