### ISSUE TITLE
Dep dropdown list won't display returned result - Uncaught error

### ISSUE THREAD

**Issue by cluwong** [kartik-v/yii2-widget-depdrop#50]
I'm getting the following error, after the Json data returned from Controller action:

Uncaught TypeError: Cannot read property 'toString' of null
    at a.createOption (dependent-dropdown.min.js:10)
    at a.renderSelect (dependent-dropdown.min.js:10)
    at Object.success (dependent-dropdown.min.js:10)
    at fire (jquery.js:3187)
    at Object.fireWith [as resolveWith] (jquery.js:3317)
    at done (jquery.js:8757)
    at XMLHttpRequest.<anonymous> (jquery.js:9123)

Using Yii 2.0.12, jQuery v2.2.4 and dependent-dropdown v1.4.7. Have tested on both Chrome and Firefox.

I haven't used this form for more than a week and the error happened today. Noticed that dependent-dropdown was updated on Jul 25. Not sure if this is related or are there any version clashes?

**Comment by denisbondar** [comment]
I have the same problem.

**Comment by kartik-v** [comment]
You need to ensure you have latest release of dependent-dropdown - currently it is v1.4.8.

**Comment by igorrarruda** [comment]
I added **dependent-dropdown** @dev branch in my composer and the problem has been resolved..

**Comment by cluwong** [comment]
Ran composer update and it's now working as normal. Thanks.
