### ISSUE TITLE
Can dropdown elements become droppable

### ISSUE THREAD

**Issue by YairHadari** [kartik-v/yii2-widget-depdrop#6]
Hi,

I"m working with depdrop widget and would like the last dropdown list elements to become droppable.
Is there a way to perform it?

Yair

**Comment by kartik-v** [comment]
Not clear... can you explain what do you mean by **droppable**?

**Comment by YairHadari** [comment]
I would like to drag an element from the dropdown list to another object on my screen

**Comment by kartik-v** [comment]
This is not in scope of the plugin... you need to implement this using other plugins OR use your javascript on the same input element to drag/drop.
