### ISSUE TITLE
Support kartik-v/yii2-krajee-base Version 2.0.0

### ISSUE THREAD

**Issue by bscheshirwork** [kartik-v/yii2-widget-depdrop#66]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-widget-depdrop.
- [ ] This is not an usage question. I confirm having gone through and read the documentation for [ActiveForm](http://demos.krajee.com/widget-details/active-form) and [ActiveField](http://demos.krajee.com/widget-details/active-field).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Install another beautifull widgets
2. Install `"kartik-v/yii2-widget-depdrop": "@dev"`
3.
``` sh
Package operations: 2 installs, 1 update, 0 removals
Installs: kartik-v/dependent-dropdown:dev-master 6aba86f, kartik-v/yii2-widget-depdrop:dev-master dce295c
Updates: kartik-v/yii2-krajee-base:v1.9.9
  - Downgrading kartik-v/yii2-krajee-base (dev-master 80a52fd => v1.9.9): Executing command (/var/www/html/vendor/kartik-v/yii2-krajee-base): git show-ref --head -d

```

## Expected behavior and actual behavior

When I follow those steps, I see...
Downgrade. I am not sure for already installed packages. After downgrading is still work? :suspect: 

I was expecting...
Support newest and make it better :+1: 

#### Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-widget-depdrop version:

## Isolating the problem

- [ ] This bug happens [on the demos page](http://demos.krajee.com/widget-details/active-form)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-widget-depdrop without other plugins.

**Comment by kartik-v** [comment]
Follow the docs for new versions of yii2-krajee-base and [read about the bootstrap info](http://demos.krajee.com/widget-details/depdrop#bs-info). You need to install manually either `yiisoft/yii2-bootstrap` for BS Version 3.x or `yiisoft/yii2-bootstrap4` for BS version 4.x
