### ISSUE TITLE
Dependency issue when using bootstrap 4 on dev-master

### ISSUE THREAD

**Issue by rubensbarreto** [kartik-v/yii2-widget-depdrop#67]
## Steps to reproduce the issue

1. Require "yiisoft/yii2-bootstrap4": "@dev"
2. Require "kartik-v/yii2-krajee-base": "dev-master"
3. Require  "kartik-v/yii2-widget-depdrop": "dev-master"

## Expected behavior and actual behavior

When I follow these steps:

Your requirements could not be resolved to an installable set of packages.                               

  Problem 1
    - Installation request for kartik-v/yii2-widget-depdrop dev-master -> satisfiable by kartik-v/yii2-widget-depdrop[dev-master].
    - kartik-v/yii2-widget-depdrop dev-master requires kartik-v/yii2-krajee-base ~1.9 -> satisfiable by kartik-v/yii2-krajee-base[v1.9.0, v1.9.1, v1.9.2, v1.9.3, v1.9.4, v1.9.5, v1.9.6, v1.9.7, v1.9.8, v1.9.9] but these conflict with your requirements or minimum-stability.

## Environment

PHP 7.2.10 (cli) (built: Sep 14 2018 07:06:17) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10, Copyright (c) 1999-2018, by Zend Technologies

Composer version 1.7.3 2018-11-01 10:05:06

#### Operating System

- Mac OS X 10.14.1

**Comment by kartik-v** [comment]
Remove yii2-krajee-base from your composer... It will get automatically installed once you install yii2-widget-depdrop

**Comment by rubensbarreto** [comment]
Thanks a lot! It worked.
