### ISSUE TITLE
Cant load subcategory if there are more than 200 rows

### ISSUE THREAD

**Issue by singhalyk86** [kartik-v/yii2-widget-depdrop#69]
If i put this into the controller than the city options come otherwise not.
$state = \backend\models\City::find()->where(['state_id' => $cat_id])->limit(101)->all();

If i remove limit(101) then the cities have less than may be 150 rows are shown in the dropdown otherwise the loader just keeps moving for 2 sec and nothing happens.

I do not know the exact amount of rows where the problem starts.

Everything works with the same setup with my previous version.

**Comment by whmemon** [comment]
Same issue is faced by me.
