### ISSUE TITLE
depdrop and datetimepicker cant composer install in one project

### ISSUE THREAD

**Issue by menglimengwai** [kartik-v/yii2-widget-depdrop#70]
depdrop and datetimepicker cant install in one project by composer，

depdrop require  "kartik-v/yii2-krajee-base": "~1.9"
but datetimepicker  require  "kartik-v/yii2-krajee-base": ">=2.0.0"

composer error 
 Can only install one of: kartik-v/yii2-krajee-base[v2.0.4, v1.9.9].

**Comment by cesarcgfg** [comment]
Same issue here

**Comment by kartik-v** [comment]
Resolved via #73.
