### ISSUE TITLE
cannot use 'in' operator to search for 'length' in

### ISSUE THREAD

**Issue by thiagomoraesp** [kartik-v/yii2-widget-depdrop#75]
Im having a problem passing the json callback to the dep drop, i double checked and the json output is working well.

The error is:

 "cannot use 'in' operator to search for 'length' in"

I already have the last version.

**Comment by thiagomoraesp** [comment]
Oh, i got it, the json return differs from the first element(where the array key is the id and the content is the description), is not this a usability issue?

**Comment by thiagomoraesp** [comment]
For those experiencing the same question(or for me in the future ;) ), the expected json output is:

{"output":[
{"id":10,"name":"item1"},
{"id":11,"name":"item2"},
]{"id":12,"name":"item3"}],
"selected":10}

**Comment by kartik-v** [comment]
Yes this is been stated in the docs. Suggest to [read documentation on expected format for dependent dropdown ajax response](http://plugins.krajee.com/dependent-dropdown#ajax-response-format).
