### ISSUE TITLE
change loading class

### ISSUE THREAD

**Issue by cluwong** [kartik-v/yii2-widget-depdrop#76]
I want to change the default loading class from kv-loading to another class:
```
<?= $form->field($model, 'group')->widget(DepDrop::classname(), [
            'data'      => $groups,
            'type'      => DepDrop::TYPE_SELECT2,
            'pluginOptions'   => [
                'depends'       => ['parentfield'],
                'placeholder'   => 'Select...',
                'url'           => ['/get-groups'],
                'loadingClass'  => 'loader',
            ],
        ]) ?>
```
But the object is still using kv-loading when the field is waiting for result. Have tried to reset assets and clear cache.

'loadingClass' is not documented in http://demos.krajee.com/widget-details/depdrop pluginOptions section, but it's available from http://plugins.krajee.com/dependent-dropdown#option-loadingClass

If this option is not included in the widget, can it be included to make use of available options from the plugin?

DepDrop V1.0.6
Plugin V1.4.9

**Comment by kartik-v** [comment]
It does work as intended. 

Remember the `loadingClass` will be applied to the dropdown elements set via `pluginOptions['depends']` .
