### ISSUE TITLE
you need to edit 'dependent-dropdown.js' in your assets directory.

### ISSUE THREAD

**Issue by tarmof** [kartik-v/yii2-widget-depdrop#77]
you need to edit 'dependent-dropdown.js' in your assets directory.
on line 97,
before: on('depdrop:change change select2:select krajeeselect2:cleared'
after: on('depdrop:change change select2:select krajeeselect2:cleared krajeeselect2:selectall krajeeselect2:unselectall'
this is help me.

_Originally posted by @fateevv85 in https://github.com/kartik-v/yii2-widget-depdrop/issues/28#issuecomment-405094045_

**Comment by tarmof** [comment]
I have done this modification, but this does not help
Select all still does not trigger any action

**Comment by tarmof** [comment]
Yes this is working, but Kartik, can You please fix this in Your code

**Comment by abriosi-benassi** [comment]
I still experience this problem.

**Comment by abriosi-benassi** [comment]
I have fixed it with this:
```
$('#your_select2_id').on('krajeeselect2:selectall krajeeselect2:unselectall',function (e) {
    $('#your_select2_id').trigger('select2:select');
});
```
