### ISSUE TITLE
Depdrop Widget default value on update?

### ISSUE THREAD

**Issue by pkjoshi** [kartik-v/yii2-widget-depdrop#8]
The Depdrop is working fine except in situation like I have not selected a value from the dependent field at the time of creation of record, then on update all the values in the dependent field are shown including the first field as selected instead of `please select` or `select...` option, which results in the first value getting saved on update
here is my code:
```
$form->field($model, 'package')->widget(DepDrop::classname(), [                            
   'data'=>ArrayHelper::map(\app\models\Package::find()->all(), 'id', 'package_name' ),
   'pluginOptions'=>[
   'depends'=>['room_category'], 
   'placeholder'=>'Select...',
   'url'=>  \yii\helpers\Url::to(['patient-detail/subcat']),               
    ]
    ])
```

**Comment by kartik-v** [comment]
You need to write the validation your own server code(either in controller action) OR implement your model attribute validation rules (e.g `required` rule) to prevent saving null / empty select inputs.

**Comment by ganesh002** [comment]
kartik-v 
I had used your all yii2 widgets its really nice, no words. I just want a small help.
I have same problem like Mr. Joshi had.
I had never used  'placeholder'=>'Select...' in plugin Options but after load ajax request the the drop down has default selected value is "Select..." and giving error - ** ID must be an integer - its integer field 
I think it comes from js file but when I inspect it by right clicking it doesn't showing <option>Select...</option> not showing 'value' parameter to this option

Please help..
Thanks in advance
