### ISSUE TITLE
how to re-initialize the depdrop?

### ISSUE THREAD

**Issue by hoangngk** [kartik-v/yii2-widget-depdrop#9]
when I used 
```
$('#which-event').depdrop();
```

to re-initialize the depdrop. but I get a error in cosole log like this:

```
Uncaught TypeError: Cannot read property 'length' of undefined

```

And  it seems it miss "depends" property in DepDrop class

**Comment by kartik-v** [comment]
You need to pass the pluginOptions inside the depdrop widget... You could parse the `data-krajee-depdrop` data attribute which stores the depdrop plugin options.
